// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

String packSignature({required String signature, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimplePackSignature(signature: signature, hint: hint);

String unpackSignature({required String compressedSignature, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleUnpackSignature(
        compressedSignature: compressedSignature, hint: hint);

String signPoseidon(
        {required String privateKey, required String msg, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleSignPoseidon(
        privateKey: privateKey, msg: msg, hint: hint);

String prv2Pub({required String privateKey, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimplePrv2Pub(privateKey: privateKey, hint: hint);

String toHexString({required List<int> bytes, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleToHexString(bytes: bytes, hint: hint);

String packPoint(
        {required String pointX, required String pointY, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimplePackPoint(pointX: pointX, pointY: pointY, hint: hint);

String unpackPoint({required String compressedPoint, dynamic hint}) => RustLib
    .instance.api
    .crateApiSimpleUnpackPoint(compressedPoint: compressedPoint, hint: hint);

String hashPoseidon({required String txCompressedData, dynamic hint}) => RustLib
    .instance.api
    .crateApiSimpleHashPoseidon(txCompressedData: txCompressedData, hint: hint);

String verifyPoseidon(
        {required String privateKey,
        required String compressedSignature,
        required String message,
        dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleVerifyPoseidon(
        privateKey: privateKey,
        compressedSignature: compressedSignature,
        message: message,
        hint: hint);
